// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Use environment variables for Supabase credentials
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_KEY;

// Ensure environment variables are defined
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error("Supabase URL and Key must be provided as environment variables VITE_SUPABASE_URL and VITE_SUPABASE_KEY.");
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Handle errors from Supabase operations (Keeping the SupabaseError class from your snippet)
export class SupabaseError extends Error {
  code: string;
  
  constructor(message: string, code: string) {
    super(message);
    this.name = 'SupabaseError';
    this.code = code;
  }
}

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  }
});